language: python
python:
    - "2.7"
before_install:
    - sudo apt-get install libjpeg8 libjpeg8-dev libjpeg-dev libfreetype6 libfreetype6-dev zlib1g-dev tree
install: pip install -r requirements.txt --use-mirrors
script: python manage.py test

