language: python
python:
    - "2.7"
before_install:
    - sudo apt-get install libtiff4-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms1-dev libwebp-dev tcl8.5-dev tk8.5-dev
install: pip install -r requirements.txt --use-mirrors
script: python manage.py test

